[package]
name = "spot_the_diff"
version = "0.1.0"
edition = "2021"

[dependencies]
dify = "0.6"
glob = "0.3"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.0"
clap = { version = "4.0", features = ["derive"] }