on: push

name: ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu,x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2.7.1
      - run: cargo test

  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
            binary-extension: .exe
    runs-on: ${{ matrix.os }}
    steps:      
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.7.1
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: release-artifacts-${{ matrix.os }}
          path: target/release/spot_the_diff${{ matrix.binary-extension }}

  release:
    # if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Download linux artifact
        uses: actions/download-artifact@v2
        with:
          name: release-artifacts-ubuntu-latest
      - name: Download windows artifact
        uses: actions/download-artifact@v2
        with:
          name: release-artifacts-windows-latest
      - run: ls -R
      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh release create ${{ github.ref_name }}
          "spot_the_diff#Linux"
          "spot_the_diff.exe#Windows"
          --generate-notes
